name: Docker CI - Conditional Deploy with Versioning

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #####################################
      # 🚀 CLIENT DEPLOYMENT
      #####################################
      - name: Check for client changes
        id: client_check
        run: |
          if git diff --quiet HEAD~1 HEAD -- ./client; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Build and push client images
        if: steps.client_check.outputs.changed == 'true'
        run: |
          docker build ./client -t alikhandevs/cloudnotes-client:latest -t alikhandevs/cloudnotes-client:${{ steps.vars.outputs.sha_short }}
          docker push alikhandevs/cloudnotes-client:latest
          docker push alikhandevs/cloudnotes-client:${{ steps.vars.outputs.sha_short }}

      - name: Trigger Render client deploy
        if: steps.client_check.outputs.changed == 'true'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      #####################################
      # 🚀 SERVER DEPLOYMENT
      #####################################
      - name: Check for server changes
        id: server_check
        run: |
          if git diff --quiet HEAD~1 HEAD -- ./server; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Build and push server images
        if: steps.server_check.outputs.changed == 'true'
        run: |
          docker build ./server -t alikhandevs/cloudnotes-server:latest -t alikhandevs/cloudnotes-server:${{ steps.vars.outputs.sha_short }}
          docker push alikhandevs/cloudnotes-server:latest
          docker push alikhandevs/cloudnotes-server:${{ steps.vars.outputs.sha_short }}

      - name: Trigger Render server deploy
        if: steps.server_check.outputs.changed == 'true'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_SERVER_HOOK }}
