name: Docker CI - Client and Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy-client:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    name: Build and Deploy Client
    # Only run this job if files in client/ directory change
    paths:
      - 'client/**'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client image
        run: |
          docker build ./client -t alikhandevs/cloudnotes-client:latest
          docker push alikhandevs/cloudnotes-client:latest

      - name: Trigger Client Render Deployment
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  build-and-deploy-server:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    name: Build and Deploy Server
    # Only run this job if files in server/ directory change
    paths:
      - 'server/**'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server image
        run: |
          docker build ./server -t alikhandevs/cloudnotes-server:latest
          docker push alikhandevs/cloudnotes-server:latest

      - name: Trigger Server Render Deployment
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_SERVER_HOOK }}
